name: Rewards Action

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Push to Git
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git push https://${{ secrets.PAT_TOKEN }}@github.com/Shashank8981/testphase.git main:main
          git push

Username: <Shashank8981>
Password: <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>
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: download
        run: |
          wget "https://drive.google.com/uc?export=download&id=1Zl62brsqmSJ60xbYg2x1nT557k6tjTTY" -O MicrosoftRewardsBot.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Main ID
        run: |
          python MicrosoftRewardsBot.py --headless --fast --emailalerts --accounts "${{ secrets.REWARDS_CREDENTIALS }}"
